export type SlackUserNotificationSeed = {
  name: string;
  email: string | null;
  slackId: string;
  isMessageEnabled: boolean;
};

const rawSlackUserNotificationSeed: Array<Omit<SlackUserNotificationSeed, 'isMessageEnabled'>> = [
  { name: 'Aayush Bajaj', email: 'aayush.bajaj@cawstudios.com', slackId: 'U04BSEJ91DG' },
  { name: 'Archita Srivastava', email: null, slackId: 'U0AFS05CQD7' },
  { name: 'Abdus Samad', email: 'abdus.samad@cawstudios.com', slackId: 'U060CMQFM6C' },
  { name: 'Ahmad Zafar Zaidi', email: 'ahmad.zaidi@caw.tech', slackId: 'U0AJVELK087' },
  { name: 'Arhan Ali Khan', email: 'arhan.khan@caw.tech', slackId: 'U0AFCU0CS0Y' },
  { name: 'Arihant Jain', email: 'arihant.jain@caw.tech', slackId: 'U0A7MQDGW95' },
  { name: 'Abhilash Bommakanti', email: 'abhilash.bommakanti@cawstudios.com', slackId: 'U01UZ3VQNVD' },
  { name: 'Alekhya Gopu', email: 'alekhya.gopu@cawstudios.com', slackId: 'U787Y0ZLP' },
  { name: 'Akhil D', email: 'akhil.d@caw.tech', slackId: 'U0AKUGX5GTU' },
  { name: 'Alen T Vinsent', email: 'alen.t@caw.tech', slackId: 'U05TQ8J0M6X' },
  { name: 'Amber Pandey', email: null, slackId: 'U0AHQ51535Y' },
  { name: 'Ameer Khan', email: 'ameer.khan@caw.tech', slackId: 'U0A3WC4QS91' },
  { name: 'Aman Singh', email: null, slackId: 'U08URQHUCDC' },
  { name: 'Anirudh K', email: null, slackId: 'U09J0CW1TFT' },
  { name: 'Aniket Purkayastha', email: 'aniket.purkayastha@cawstudios.com', slackId: 'U03FCRTMYJG' },
  { name: 'Anil Chauhan', email: 'anil.chauhan@cawstudios.com', slackId: 'U02UMCZAQ0Z' },
  { name: 'Aryan Thakur', email: 'aryan.thakur@cawstudios.com', slackId: 'U03J4KHDWB0' },
  { name: 'Ashirwad Pramod Shetye', email: null, slackId: 'U09QQLPDC7K' },
  { name: 'Ayush Gupta', email: 'ayush.gupta@cawstudios.com', slackId: 'U09GFRNM4TV' },
  { name: 'Baskar Harshine', email: null, slackId: 'U08URQG6CUE' },
  { name: 'Bokka Pardha Sarathi Reddy', email: 'pardhasarathi.b@caw.tech', slackId: 'U09R5TH83QQ' },
  { name: 'Bilal Ashraf', email: null, slackId: 'U09FARY3AD9' },
  { name: 'Bommani Bharath', email: null, slackId: 'U09V48P930B' },
  { name: 'Bhargav Reddy', email: 'bhargav.v@caw.tech', slackId: 'U0A7MRLARLY' },
  { name: 'C Akshay', email: null, slackId: 'U09MF7DG527' },
  { name: 'Chandradeep Kumar', email: 'chandradeep.kumar@cawstudios.com', slackId: 'U026H7CT058' },
  { name: 'Charitha Naidu', email: 'charitha.naidu@cawstudios.com', slackId: 'U04EN41PDBK' },
  { name: 'Chenna Mithin Kumar', email: null, slackId: 'U09MF7F3BC3' },
  { name: 'Chetan Singh', email: 'chetan.singh@cawstudios.com', slackId: 'U05FALLTQMA' },
  { name: 'Gowrishankar K', email: 'gowrishankar.k@caw.tech', slackId: 'U0AF49TBL7Q' },
  { name: 'G Sai charan', email: null, slackId: 'U0A4HN2HT7Z' },
  { name: 'Geetika Agarwal', email: 'geetika.agarwal@caw.tech', slackId: 'U09NBS2AL4X' },
  { name: 'Haris Rahman', email: 'haris.rahman@cawstudios.com', slackId: 'U05LK57D87J' },
  { name: 'Hemant Agrawal', email: 'hemant.agrawal@cawstudios.com', slackId: 'U056EUUCCB0' },
  { name: 'Himanshu Kumar', email: 'himanshu.kumar@cawstudios.com', slackId: 'U049QFS4BBL' },
  { name: 'Jayanth Ponnada', email: 'jayanth.ponnada@cawstudios.com', slackId: 'U0AE3DMT27M' },
  { name: 'Kallem Ravali', email: 'ravali.k@caw.tech', slackId: 'U04UVU37SNP' },
  { name: 'Kalagotla Suhas', email: 'suhas.kalagotla@caw.tech', slackId: 'U0838UDAX3N' },
  { name: 'Karthick Kumar', email: 'karthick.k@cawstudios.com', slackId: 'U039Z5XTE76' },
  { name: 'Kartik Bansal', email: 'kartik.bansal@cawstudios.com', slackId: 'U667CPUF6' },
  { name: 'Kashish Chugh', email: 'kashish.chugh@cawstudios.com', slackId: 'U04BBTZ2Y3Z' },
  { name: 'Krishna Madisetty', email: 'krishna.madisetty@cawstudios.com', slackId: 'U08KBQKJQ1M' },
  { name: 'Krishnaveni Bhogapurapu', email: 'krishnaveni.b@cawstudios.com', slackId: 'UTW3DPYTH' },
  { name: 'Korra Manjula', email: null, slackId: 'U09FM6NH0MC' },
  { name: 'Kirti Padhi', email: 'kirti.padhi@caw.tech', slackId: 'U0AEM1AV7LK' },
  { name: 'Kommula Lakshmi Sai Sravanthi', email: null, slackId: 'U09Q9B572AJ' },
  { name: 'Kusumanchi Eswar Ashish', email: 'eshwar.ashish@cawstudios.com', slackId: 'U08F16F70N5' },
  { name: 'Mahtv Bansal', email: null, slackId: 'U08J1BNG6FM' },
  { name: 'Manda Neel Gagan', email: 'neel.gagan@cawstudios.com', slackId: 'U04JC5KSC01' },
  { name: 'Mandumula Nandeshwar Reddy', email: 'nandeshwar.reddy@cawstudios.com', slackId: 'U05NP2HTU8J' },
  { name: 'Manish Mangla', email: 'manish.mangla@cawstudios.com', slackId: 'U03HWKFH6JK' },
  { name: 'Mary Das', email: null, slackId: 'U09AR63ACFJ' },
  { name: 'Mayankana Gupta', email: 'mayankana.gupta@cawstudios.com', slackId: 'U015F4HG1PA' },
  { name: 'MK. Revan', email: null, slackId: 'U09F43RQUN9' },
  { name: 'Mounica E', email: null, slackId: 'U0A017NH22Z' },
  { name: 'Mohd Farhan Ansari', email: null, slackId: 'U0A5DUC7PPB' },
  { name: 'Naveen V', email: 'naveen.v@caw.tech', slackId: 'U0AF2UFTJH3' },
  { name: 'Naveen Kumar Sandula', email: null, slackId: 'U02ECCEEE5A' },
  { name: 'Nanda Kishore SM', email: null, slackId: 'U0A1E2GSBF0' },
  { name: 'Neeraj Banadru', email: 'neeraj.bandaru@cawstudios.com', slackId: 'U069ACJPWLE' },
  { name: 'Peraka Dola Naga Syam Kumar', email: 'syamkumar.pd@cawstudios.com', slackId: 'U04UFG4M7SB' },
  { name: 'Pilli Ram Durga Prasad', email: 'ramdurgaprasad.p@caw.tech', slackId: 'U0AHF5TD74P' },
  { name: 'Prameela Nannapaneni', email: 'prameela.nannapaneni@cawstudios.com', slackId: 'U05FXUJ8DA4' },
  { name: 'Pramod Varma', email: 'pramod.varma@cawstudios.com', slackId: 'U0637NVS79P' },
  { name: 'Pranali Sawale', email: 'pranali.s@cawstudios.com', slackId: 'U03E222121F' },
  { name: 'Rahul Anand', email: 'rahul.anand@caw.tech', slackId: 'U0A5YQ63CMT' },
  { name: 'Rahul Balasaheb Kandhare', email: null, slackId: 'U07G21A6A6B' },
  { name: 'Rahul Balu Khadse', email: null, slackId: 'U08TCTDMP0A' },
  { name: 'Ranjana Singh', email: 'ranjana@cawstudios.com', slackId: 'U02S12N64MV' },
  { name: 'Raj Karmakar', email: 'raj.karmakar@caw.tech', slackId: 'U0A8170HTRC' },
  { name: 'RaviKiran V', email: 'ravikiran.v@cawstudios.com', slackId: 'U76FH44L8' },
  { name: 'Rudraksh Chandel', email: null, slackId: 'U09U6EJ1RMW' },
  { name: 'Sai Charan Guntupalli', email: null, slackId: 'U08GGRP0RM5' },
  { name: 'Sai Kumar Perumalla', email: 'saikumar.p@caw.tech', slackId: 'U0A60G9FD0U' },
  { name: 'Sakaram Ruchitha', email: 'ruchitha.sakaram@caw.tech', slackId: 'U0844G6PS9X' },
  { name: 'Shalini Tripathi', email: null, slackId: 'U08P6PWBUAK' },
  { name: 'Shivom Srivastava', email: 'shivom.srivastava@cawstudios.com', slackId: 'U065PU8H58V' },
  { name: 'Shorya Sharma', email: 'shorya.sharma@cawstudios.com', slackId: 'U05BT9Q9X70' },
  { name: 'Shrey Agrawal', email: 'shrey.agrawal@cawstudios.com', slackId: 'U03H87GGPAB' },
  { name: 'Shuaib Ahmed', email: null, slackId: 'U09R5TFRH08' },
  { name: 'Shreyas Sane', email: 'shreyas.sane@cawstudios.com', slackId: 'U024LDHAVS4' },
  { name: 'SG Amulya', email: null, slackId: 'U09F43SSCPP' },
  { name: 'Sri Harsha S', email: null, slackId: 'U09J0CVL73K' },
  { name: 'Sriniketh Reddy', email: 'sriniketh.sr@caw.tech', slackId: 'U09JSK0MLBF' },
  { name: 'Sriram M Pant', email: null, slackId: 'U09G9C12ZJP' },
  { name: 'Srinivasrao L', email: 'srinivasrao.l@cawstudios.com', slackId: 'U772B8F0T' },
  { name: 'Stuti Jain', email: 'stuti.jain@cawstudios.com', slackId: 'U03DR1X1QKH' },
  { name: 'Suvarna Varigala', email: null, slackId: 'U07VCDMAW1W' },
  { name: 'Taavish Thaman', email: 'taavish.t@caw.tech', slackId: 'U0A5C3G5N9F' },
  { name: 'Tejas Dattatray Ligade', email: 'tejas.dl@cawstudios.com', slackId: 'U051HK4LGRJ' },
  { name: 'Tithi Das', email: 'tithi.das@cawstudios.com', slackId: 'U05V1JYMG3U' },
  { name: 'Tushar Mavi', email: 'tushar.mavi@cawstudios.com', slackId: 'U04CG5S1AQY' },
  { name: 'Tushar Swarup Tandon', email: 'tushar.tandon@cawstudios.com', slackId: 'U03FAEZ6H42' },
  { name: 'Vedika Heda', email: null, slackId: 'U08QHC4R926' },
  { name: 'Kottu Rama Naga Vishnu Kumar', email: 'vishnuKumar.k@caw.tech', slackId: 'U08U8DWNWTH' },
  { name: 'Vaishnavi Tadaka', email: 'vaishnavi.tadaka@caw.tech', slackId: 'U08CHF272JW' },
  { name: 'Vishnupriya A', email: null, slackId: 'U09GP1Y6ZUK' },
  { name: 'Yeggoni Jayanth Pushparaju', email: 'jayanth.py@cawstudios.com', slackId: 'U051F1H69GB' }
];

export const slackUserNotificationSeed: SlackUserNotificationSeed[] = rawSlackUserNotificationSeed.map((user) => ({
  ...user,
  isMessageEnabled: false
}));
